# PRÁCTICA DE NUMPY

Para la realización de la práctica, debe buscarse información de las siguientes métodos de Numpy: nditer, unique, min, argmin, ravel, flatten, inner, percentile, astype, np.NaN, isnan, nonzero, stack, array_split, average, shuffle, normal, around.

0.- Importa el paquete numpy

In [2]:
import numpy as np

1.- Crear dos array a partir de sendas listas de enteros. En el segundo de ellos, indicar que el array debe ser de tipo *float*

In [3]:
lista1=[1,3,5]
lista2=[5,7,8]
array1=np.array(lista1)
array2=np.array(lista2,dtype=float)
print(array1,'\n' , array2)



[1 3 5] 
 [5. 7. 8.]


2.- Crea tres arrays: uno de ceros otro de unos y otro de cincos. Todos tendrán cuatro elementos. 

In [4]:
print(np.zeros([1,4]), '\n', np.ones([1,4]), '\n' , np.ones([1,4])*5)

[[0. 0. 0. 0.]] 
 [[1. 1. 1. 1.]] 
 [[5. 5. 5. 5.]]


3.- Crea un array unidimensional de doce elementos (valores del 1 al 12) y reorganízalo como un array 2D de 3x4. Recórrelo y muestra sus elementos.
Mostrar por pantalla las dimensiones de la matriz usando el campo *shape*

In [5]:
array1=np.arange(1,13,1)
array1=array1.reshape(3,4)
print(array1)
print(array1.shape)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


4.- Crear un array 1D con 20 valores aleatorios entre 0 y 10 y luego cámbiales el signo a los mayores de 5 (intenta evitar los bucles usando indexación buleana).

In [6]:
array1=np.random.randint(0,10,20)
print(array1)
array1[(array1>5)]=-array1[(array1>5)]
print(array1)


[2 4 5 8 5 7 3 7 8 2 6 3 7 4 9 9 7 8 5 4]
[ 2  4  5 -8  5 -7  3 -7 -8  2 -6  3 -7  4 -9 -9 -7 -8  5  4]


5.- Crea un array 2x2 a partir de una lista y muestra lo siguiente:
*   La suma de todos los elementos.
*   La suma de cada columna
*   La suma de cada fila

In [7]:
array1=np.random.randint(0,2,4)
array1=array1.reshape(2,2)
print(array1)
print(array1.sum())
print(array1.sum(axis=0))
print(array1.sum(axis=1))

[[1 1]
 [1 0]]
3
[2 1]
[2 1]


6.- Convertir un array con grados Fahrenheit a centígrados, usando una operación de vector (por tanto, sin hacerlo elemento a elemento).

In [8]:
arrayF=np.array([0, 12, 45.21, 34, 99.91],dtype=float)
print(arrayF)
arrayC=(arrayF-32)*5/9
print(arrayC)

[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


7.- Devuelve los elementos de un array 2D, eliminando los repetidos.

In [9]:
array1=np.array([10,10,20,20,30,30])
print(array1)
array1=np.unique(array1)
print(array1)


[10 10 20 20 30 30]
[10 20 30]


8.- Crear un array unidimensional con 6 de enteros aleatorios entre 1 y 49 y mostrar las posiciones del máximo y del mínimo.

In [17]:
array1=np.random.randint(1,49,6)
print(array1)
print(array1.argmax())
print(array1.argmin())




[40 26 31 10 34 25]
0
3


9.- Crear un array bidimensional y calcular la posición del máximo de cada fila y del mínimo de cada columna.

In [23]:
array1=np.random.randint(1,49,6)
array1=array1.reshape(2,3)
print(array1)
print(array1.argmax(axis=0))
print(array1.argmin(axis=1))


[[ 4 18  7]
 [ 2 23 34]]
[0 1 1]
[0 0]


10.- Usa las funciones `reshape`, `flatten` o `ravel` para aplanar un vector: guardar los mismos valores en el mismo orden en un vector 1D.

In [36]:
array1=np.array([[3,5,1],[2,7,0]])
print(array1)
print(array1.reshape(6))
print(array1.flatten())
print(array1.ravel())




[[3 5 1]
 [2 7 0]]
[3 5 1 2 7 0]
[3 5 1 2 7 0]
[3 5 1 2 7 0]


11.- Calcular el producto matricial (fila por columna) y la suma de dos arrays 2x2.

Producto:
 [[18  5]
 [30  9]]

Suma:
 [[1 5]
 [8 6]]


12.- Calcula la inversa y el determinante de una matriz cuadrada 2D:

[[1 3 5]
 [2 2 4]
 [6 7 8]]

Determinante: 21.999999999999996

Inversa:
 [[-0.54545455  0.5         0.09090909]
 [ 0.36363636 -1.          0.27272727]
 [ 0.09090909  0.5        -0.18181818]]


13.- Calcula el producto interno de dos arrays unidimensionales de 3 elementos.

Producto interno: 44


14.- Ordenar un array unidimensional.

[43 33  5 35 38 35]
[ 5 33 35 35 38 43]


15.- Calcular el percentil 80 de los elementos de un array unidimensional de once elementos.

[ 2  8 15 30 34 45 65 71 77 82 91] -> 77.0


16.- Calcular el promedio y la varianza de array del ejercicio anterior. 

Promedio: 47.27272727272727
Varianza: 908.3801652892562


17.- Cambiar el tipo de dato de los elementos del array del ejercicio anterior a *float*.

[ 2  8 15 30 34 45 65 71 77 82 91] 
 [ 2.  8. 15. 30. 34. 45. 65. 71. 77. 82. 91.]


18.- Al array de valores reales (*float*) del ejercicio anterior, asignar el valor NaN a tres posciones cualesquiera. Usa indexación lógica (buleana) para mostrar los distintos a NaN.

[ 2.  8. nan 30. nan 45. 65. 71. nan 82. 91.]
[ 2.  8. 30. 45. 65. 71. 82. 91.]


19.- Indicar las posiciones distintas de cero de un array 3x2, usando la función `np.nonzero`.

[[5 2]
 [0 8]
 [7 0]]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))


20.- Usar el método `np.stack` para apilar tres arrays unidimensionales de dos elementos para formar una array 3x2  (los arrays serán las filas).

[[1 6]
 [2 7]
 [3 8]]


21.- Usar el método `np.stack` para apilar tres arrays unidimensionales de dos elementos para formar una array 2x3 (los arrays serán las columnas).

[[1 2 3]
 [6 7 8]]


22.- Usar el método `np.hstack` para generar un nuevo array unidimensional como la concatenación de los tres anteriores (a1, a2 y a3).

[1 6 2 7 3 8]


23.- Dividir por la mitad un array de seis posiciones. Dividirlo también en tres arrays de igual tamaño y mostrarlos uno por uno iterando la lista de nuevos arrays.

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]
[1 2]
[3 4]
[5 6]


24.- Crear un array bidimensional de 2 filas y 3 columnas y calcular la media ponderada de cada columna, como el 70% del elemento de la primera fila y el 30% del elemento de la segunda.

Media ponderada: [8.3 2.7 6.1]


25.- Dado un array unidimensional, desordena de forma aleatoria sus elementos.

[5 2 0 3 4 1]


26.- Genera un array 2x3 de valores aleatorios con distribución normal de media=2 y desviación estándar=3.

[[ 3.68951384  2.03430092 -1.46480026]
 [ 0.189432    9.25526573  4.30121563]]


27.- Simula una neurona artificial (*perceptrón*): tendremos n entradas numéricas entre 0 y 1 (array), n pesos entre 0 y 1 (*array*). Para calcular la salida de la neurona se hará la suma de las entradas, cada una de ellas ponderada por su peso y si el resultado es mayor que n*0.25, la neurona producirá un uno, en caso contrario, un cero.
<p><br></p>
<img src="https://www.llipe.com/wp-content/uploads/2017/04/modelo-perceptron-simple-740.jpg" width="500">

Entradas: [0.852 0.726 0.627 0.569]
Pesos:    [0.556 0.607 0.683 0.046]
Suma ponderada: 1.369
Resultado 1
