# PRÁCTICA DE NUMPY

## Resumen de métodos y funciones utilizados

In [24]:
# Importa numpy:
import numpy as np

1.- Crear dos array a partir de sendas listas de enteros. En el segundo de ellos, indicar que el array debe ser de tipo *float*

In [25]:
a = np.array([1,3,5])
b = np.array([5,7,8], dtype=float)
print(a,"\n",b)

[1 3 5] 
 [5. 7. 8.]


2.- Crea tres arrays: uno de ceros otro de unos y otro de cincos. Todos tendrán cuatro elementos.

In [26]:
a1 = np.zeros(4)
print("Array de 4 ceros:", a1)
a2 = np.ones(4)
print("Array de 4 unos:", a2)
a3 = np.ones(4)*5
print("Array de 4 cincos:", a3)


Array de 4 ceros: [0. 0. 0. 0.]
Array de 4 unos: [1. 1. 1. 1.]
Array de 4 cincos: [5. 5. 5. 5.]


3.- Crea un array unidimensional de doce elementos (valores del 1 al 12) y reorganízalo como un array 2D de 3x4. Recórrelo y muestra sus elementos.
Mostrar por pantalla las dimensiones de la matriz usando el campo *shape*

In [27]:
a = np.arange(1,13).reshape((3, 4))
print("Array:\n", a)
print("Elementos:")
for x in np.nditer(a):
  print(x,end=" ")
print("\nDimensiones:",a.shape)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elementos:
1 2 3 4 5 6 7 8 9 10 11 12 
Dimensiones: (3, 4)


4.- Crear un array 1D con 20 valores aleatorios entre 0 y 10 y luego cámbiales el signo a los mayores de 5 (intenta evitar los bucles usando indexación buleana).

In [28]:
a = np.random.randint(0, 10, size=20)
a[(a >= 5)] *= -1
a

array([-8,  2,  2, -5, -8, -6,  3,  1, -5, -8, -6,  3, -8, -7, -8, -7,  1,
        2,  0,  4])

5.- Crea un array 2x2 a partir de una lista y muestra lo siguiente:
*   La suma de todos los elementos.
*   La suma de cada columna
*   La suma de cada fila

In [29]:
x = np.array([[0,1],[2,3]])
print("Suma de todos los elementos:", np.sum(x))
print("Promedio de cada columna:", np.mean(x, axis=0))
print("Máximo de cada fila:", np.max(x, axis=1))


Suma de todos los elementos: 6
Promedio de cada columna: [1. 2.]
Máximo de cada fila: [1 3]


6.- Convertir un array con grados Fahrenheit a centígrados, usando una operación de vector (por tanto, sin hacerlo elemento a elemento).

In [30]:
af = np.array([0, 12, 45.21, 34, 99.91])
print("Valores en ºF:", af)
print("Valores en ºC:", (af-32)*5/9)


Valores en ºF: [ 0.   12.   45.21 34.   99.91]
Valores en ºC: [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


7.- Devuelve los elementos de un array 2D, eliminando los repetidos.

In [31]:
x = np.array([10, 10, 20, 20, 30, 30])
print("Array original:",x)
print("Elementos únicos (sin repetidos):", np.unique(x))


Array original: [10 10 20 20 30 30]
Elementos únicos (sin repetidos): [10 20 30]


8.- Crear un array unidimensional con 6 de enteros aleatorios entre 1 y 49 y mostrar las posiciones del máximo y del mínimo.

In [32]:
a = np.random.randint(1, 49, size=6)
print(a)
print('Índice del mínimo', np.argmin(a))
print('Índice del máximo', np.argmax(a))


[ 1 19 31  2 22 31]
Índice del mínimo 0
Índice del máximo 2


9.- Crear un array bidimensional y calcular la posición del máximo de cada fila y del mínimo de cada columna.

In [33]:
x = np.array([[3, 5, 1], [2, 7, 0]])

print("Mínimo de cada columna             :", np.min(x, axis=0))
print("Posición del mínimo de cada columna:", np.argmin(x, axis=0))
print("\nMáximo de cada fila             :", np.max(x, axis=1))
print("Posición del máximo de cada fila:", np.argmax(x, axis=1))

Mínimo de cada columna             : [2 5 0]
Posición del mínimo de cada columna: [1 0 1]

Máximo de cada fila             : [5 7]
Posición del máximo de cada fila: [1 1]


10.- Usa las funciones `reshape`, `flatten` o `ravel` para aplanar un vector: guardar los mismos valores en el mismo orden en un vector 1D.

In [34]:
plano1 = np.ravel(x)
print("Array aplanado con 'ravel':  ", plano1)
plano2 = x.flatten()
print("Array aplanado con 'flatten':", plano2)
plano3 = x.reshape(-1)
print("Array aplanado con 'flatten':", plano3)
print("\nArray original:\n",x)


Array aplanado con 'ravel':   [3 5 1 2 7 0]
Array aplanado con 'flatten': [3 5 1 2 7 0]
Array aplanado con 'flatten': [3 5 1 2 7 0]

Array original:
 [[3 5 1]
 [2 7 0]]


11.- Calcular el producto matricial (fila por columna) y la suma de dos arrays 2x2.

In [35]:
m1 = np.array([[1,3],[2,5]])
m2 = np.array([[0,2],[6,1]])
print("Producto:\n", np.dot(m1,m2))
print("\nSuma:\n", np.add(m1,m2))

Producto:
 [[18  5]
 [30  9]]

Suma:
 [[1 5]
 [8 6]]


12.- Calcula la inversa y el determinante de una matriz cuadrada 2D:

In [36]:
m = np.array([[1,3,5],[2,2,4],[6,7,8]])
print(m)
print('\nDeterminante:',np.linalg.det(m))
inversa = np.linalg.inv(m)
print('\nInversa:\n',np.linalg.inv(m))


[[1 3 5]
 [2 2 4]
 [6 7 8]]

Determinante: 21.999999999999996

Inversa:
 [[-0.54545455  0.5         0.09090909]
 [ 0.36363636 -1.          0.27272727]
 [ 0.09090909  0.5        -0.18181818]]


13.- Calcula el producto interno de dos arrays unidimensionales de 3 elementos.

In [37]:
a1 = np.array([1,3,5])
a2 = np.array([2,4,6])
print("Producto interno:", np.inner(a1, a2))

Producto interno: 44


14.- Ordenar un array unidimensional.

In [38]:
a = np.random.randint(1, 100, size=6)
print(a)
print()
a.sort()
print(a)

[90 63 47 68 90 18]

[18 47 63 68 90 90]


15.- Calcular el percentil 80 de los elementos de un array unidimensional de once elementos.

In [39]:
a = np.array([2, 8, 15, 30, 34, 45, 65, 71, 77, 82, 91])
p80 = np.percentile(a,80)
print(a,'->',p80)

[ 2  8 15 30 34 45 65 71 77 82 91] -> 77.0


16.- Calcular el promedio y la varianza de array del ejercicio anterior.

In [40]:
print('Promedio:', a.mean())
print('Varianza:', a.var())

Promedio: 47.27272727272727
Varianza: 908.3801652892562


17.- Cambiar el tipo de dato de los elementos del array del ejercicio anterior a *float*.

In [41]:
afloat = a.astype(float)
print(a,'\n',afloat)

[ 2  8 15 30 34 45 65 71 77 82 91] 
 [ 2.  8. 15. 30. 34. 45. 65. 71. 77. 82. 91.]


18.- Al array de valores reales (*float*) del ejercicio anterior, asignar el valor NaN a tres posciones cualesquiera. Usa indexación lógica (buleana) para mostrar los distintos a NaN.

In [42]:
afloat[2] = afloat[4] = afloat[8] = np.nan
print(afloat)
print(afloat[~np.isnan(afloat)])


[ 2.  8. nan 30. nan 45. 65. 71. nan 82. 91.]
[ 2.  8. 30. 45. 65. 71. 82. 91.]


19.- Indicar las posiciones distintas de cero de un array 3x2, usando la función `np.nonzero`.

In [43]:
a = np.array([[5,2],[0,8],[7,0]])
print (a)
print(np.nonzero(a))

[[5 2]
 [0 8]
 [7 0]]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))


20.- Usar el método `np.stack` para apilar tres arrays unidimensionales de dos elementos para formar una array 3x2  (los arrays serán las filas).

In [44]:
a1 = np.array([1,6])
a2 = np.array([2,7])
a3 = np.array([3,8])
m  = np.stack((a1,a2,a3)) # ojo a los dobles paréntesis
print(m)

[[1 6]
 [2 7]
 [3 8]]


21.- Usar el método `np.stack` para apilar tres arrays unidimensionales de dos elementos para formar una array 2x3 (los arrays serán las columnas).

In [45]:
m2  = np.stack((a1,a2,a3),axis=1) # ojo a los dobles paréntesis
print(m2)

[[1 2 3]
 [6 7 8]]


22.- Usar el método `np.hstack` para generar un nuevo array unidimensional como la concatenación de los tres anteriores (a1, a2 y a3).

In [46]:
m3 = np.hstack((a1,a2,a3))
print(m3)

[1 6 2 7 3 8]


23.- Dividir por la mitad un array de seis posiciones. Dividirlo también en tres arrays de igual tamaño y mostrarlos uno por uno iterando la lista de nuevos arrays.

In [47]:
a = np.arange(1,7)
print(a)
amitad = np.array_split(a,2)
print(amitad)
entres = np.array_split(a,3)
for a3 in entres:
  print(a3)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]
[1 2]
[3 4]
[5 6]


24.- Crear un array bidimensional de 2 filas y 3 columnas y calcular la media ponderada de cada columna, como el 70% del elemento de la primera fila y el 30% del elemento de la segunda.

In [48]:
a = np.array([[8,3,7],[9,2,4]])
pesos = np.array([0.7,0.3])
mp = np.average(a,weights=pesos, axis=0)
# suma ponderada dividida por la suma de los pesos: (8*0.7 + 9*0.3)/(0.7+0.3)=8.3
print('Media ponderada:', mp)

Media ponderada: [8.3 2.7 6.1]


25.- Dado un array unidimensional, desordena de forma aleatoria sus elementos.

In [49]:
a = np.array([0, 1, 2, 3, 4, 5])
np.random.shuffle(a)
print(a)
# np.random.permutation(a) -> devuelve copia y no modifica original

[3 1 5 4 2 0]


26.- Genera un array 2x3 de valores aleatorios con distribución normal de media=2 y desviación estándar=3.

In [50]:
a = np.random.normal(loc=2, scale=3, size=(2, 3)) # media=2, desv. std=3
print(a)

[[ 3.8600168  -1.92214677  7.00690227]
 [ 2.06853292  1.38409584  1.91665055]]


27.- Simula una neurona artificial (*perceptrón*): tendremos n entradas numéricas entre 0 y 1 (array), n pesos entre 0 y 1 (*array*). Para calcular la salida de la neurona se hará la suma de las entradas, cada una de ellas ponderada por su peso y si el resultado es mayor que n*0.25, la neurona producirá un uno, en caso contrario, un cero.
<p><br></p>
<img src="https://www.llipe.com/wp-content/uploads/2017/04/modelo-perceptron-simple-740.jpg" width="500">

In [59]:
n = 4
entradas = np.random.rand(n)
entradas = np.around(entradas, decimals=3)
print("Entradas:", entradas)

pesos = np.around(np.random.rand(n), decimals=3)
print("Pesos:   ", pesos)

sumaPonderada = np.inner(pesos, entradas)
sumaPonderada = np.around(sumaPonderada, decimals=3)
print("Suma ponderada:", sumaPonderada)

if (sumaPonderada >= 0.25*n):
  resultado = 1
else:
  resultado = 0

print('Resultado', resultado)

Entradas: [0.38  0.818 0.37  0.582]
Pesos:    [0.712 0.052 0.793 0.999]
Suma ponderada: 1.188
Resultado 1
